### ISSUE TITLE
Doesn't work with VS2019 

### ISSUE THREAD

**Issue by long-nguyenxuan** [FireflyMigration/ClassOutline#11]
Dear @stickleprojects 
Does this extension work with VS2019? I tried it in VS2019 and it failed to outline my class. 
Below is ScreeShot 
![image](https://user-images.githubusercontent.com/46129500/76503501-9c56aa80-6478-11ea-93be-d0bb2a7a101e.png)

**Comment by noam-honig** [comment]
It seems like it works fine, the outline is intended to show classes and inner classes - in this case, you only have the FrmMekaCorrect class and it showed it correctly.

Try adding an inner class and see the effect on the class outline.

**Comment by long-nguyenxuan** [comment]
@noam-honig  checked with #6 , understood, thanks.
