### ISSUE TITLE
On VS2017 shows nothing

### ISSUE THREAD

**Issue by robjuca** [FireflyMigration/ClassOutline#6]
Can you help me I can see nothing...
![new bitmap image](https://cloud.githubusercontent.com/assets/12336342/24518414/54e42762-1558-11e7-8c84-f81eee3891fa.jpg)
![new bitmap image 2](https://cloud.githubusercontent.com/assets/12336342/24518425/5b5d952e-1558-11e7-8040-d0448b746aff.jpg)

**Comment by stickleprojects** [comment]
Hi
Go to View, Other Windows, Class Outline. When you are looking at a c-sharp
file, you will see the tree
[image: Inline images 1]

**Comment by robjuca** [comment]
Hi,
Ok now I can see the Class Outline window BUT only "#region" is show in menu. No class tree.

![new bitmap image](https://cloud.githubusercontent.com/assets/12336342/24546565/412483ae-15e2-11e7-8957-0cdcb9e2716d.jpg)

**Comment by stickleprojects** [comment]
This class outline only shows the current class and child classes; it does not show methods and functions.
If you wish to list methods and functions perhaps a different extension would be better
